
规则IB_OM_RULE_INFO 表

  RULE_NO	规则编号
  RULE_TYP_CD	规则类型代码
  HOLI_FLG	节假日标志
  RULE_TRI_POSITION	规则触发位置
  SUIT_CHNL_SCP	适用渠道范围
  SUIT_LPR_SCP	适用法人范围
  SUIT_ORG_SCP	适用机构范围
  SUIT_TX_SCP	适用交易范围
  RULE_COMNT	规则说明
  EFFT_FLG	生效标志
  OPER_TELR_NO	操作柜员号
  OPER_TM	操作时间
  OPER_RSN	操作原因

条件IB_OM_RULECOND_INFO
  OPRTN_COND_NO	运营条件编号
  DICTRY_NM	字典名称
  OPER_SYM_1	运算符号1
  CMPR_VAL	比较值
  OPER_SYM_2	运算符号2
  VALUE2	比较值2
  TRAN_CD	交易码
  COND_DESC	条件描述
  OPER_TELR_NO	操作柜员号
  OPER_TM	操作时间
  OPER_RSN	操作原因
  CMPR_VAL_DATA_DICTRY_FLG	比较值数据字典标志
  PUB_DICTRY_FLG	公共字典标志
  DICTRY_DESC	字典描述


规则条件映射IB_OM_RULECOND_RLT

  RULE_COND_NO	CMPL_MODE_FLG	OPRTN_RULE_NO

授权模式IB_OM_AUTHMODE_INFO

    MODE_NO	模式编号
    AUTH_TYP_CD	授权类型代码
    AUTH_LVL_CD	授权级别代码
    REMOTE_AUTH_LVL_CD	远程授权级别代码
    AUTH_ORG_TYP_CD	授权机构类型代码
    AUTH_ORG_NO	授权机构号
    AUTH_POST_NO	授权岗位编号
    UGNT_FLG	加急标志
    AUTH_DESC	授权描述
    HOST_AUTH_FLG	主机授权标志
    HOST_AUTH_TYP_CD	主机授权类型代码
    CNTRTN_AUTH_CENT_NM	集中授权中心名称
    CNTRTN_AUTH_LVL_CD	集中授权级别代码
    REMRK_1	备注1
    APP_NO	应用编号


字段映射TE_PARA_TRANKEYWORDS_INFO

    TRAN_CD	交易码
    PUB_DICTRY_NM	公共字典名称
    PRIV_DICTRY_NM	私有字典名称
    PULDW_MAPG_DICTRY_NM	下拉映射字典名称

字典要素IB_PARA_KEYWORDS_INFO

  DICTRY_NM	字典名称
  DICTRY_DESC	字典描述
  DICTRY_TYP_CD	字典类型代码
  FIELD_CMPR	字段比较符
  DATA_ATTR_DESC	数据属性描述


-- 授权查询
SELECT 
CONDS.SUIT_TX_SCP TRAN_CODE,
CONDS.RULE_NO,
CONDS.COND_NO,
MODE.MODE_NO,
MODE.AUTH_TYP_CD,
MODE.AUTH_LVL_CD,
MODE.AUTH_DESC,
COND.DICTRY_NM,
COND.OPER_SYM_1,
COND.CMPR_VAL,
COND.OPER_SYM_2,
COND.VALUE2,
CONDS.EFFT_FLG,
CONDS.CMPL_MODE_FLG,

CONDS.RULE_TYP_CD,
CONDS.HOLI_FLG,
CONDS.RULE_TRI_POSITION,
CONDS.SUIT_CHNL_SCP,
CONDS.SUIT_LPR_SCP,
CONDS.SUIT_ORG_SCP,
CONDS.RULE_COMNT,
CONDS.OPER_TELR_NO,
CONDS.OPER_TM,
CONDS.OPER_RSN,
COND.OPRTN_COND_NO,
COND.TRAN_CD,
COND.COND_DESC,
COND.OPER_TELR_NO,
COND.OPER_TM,
COND.OPER_RSN,
COND.CMPR_VAL_DATA_DICTRY_FLG,
COND.PUB_DICTRY_FLG,
COND.DICTRY_DESC,
MODE.REMOTE_AUTH_LVL_CD,
MODE.AUTH_ORG_TYP_CD,
MODE.AUTH_ORG_NO,
MODE.AUTH_POST_NO,
MODE.UGNT_FLG,
MODE.HOST_AUTH_FLG,
MODE.HOST_AUTH_TYP_CD,
MODE.CNTRTN_AUTH_CENT_NM,
MODE.CNTRTN_AUTH_LVL_CD,
MODE.REMRK_1,
MODE.APP_NO
FROM
IB_OM_RULECOND_INFO COND 
LEFT JOIN
(
  SELECT RULE_COND.RULE_COND_NO COND_NO,RULE_COND.CMPL_MODE_FLG,RULE.* FROM IB_OM_RULE_INFO RULE,IB_OM_RULECOND_RLT RULE_COND
  WHERE RULE.SUIT_TX_SCP = '00102001_1' AND RULE.RULE_NO = RULE_COND.OPRTN_RULE_NO
)CONDS
ON COND.OPRTN_COND_NO = CONDS.COND_NO
LEFT JOIN 
IB_OM_AUTHMODE_INFO MODE
ON MODE.MODE_NO = COND.OPRTN_COND_NO

























